name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install -y libcfitsio-dev
    - name: Build
      run: compile/gcc-linux.sh
    - name: Test
      run: test/test.sh
